import { createSlice } from "@reduxjs/toolkit";
import type { PayloadAction } from "@reduxjs/toolkit";
import type { AuthState, AuthResponse } from "./types";
import { loginThunk, logoutThunk } from "./authThunks";

// The initial authentication state before any user logs in
const initialState: AuthState = {
  user: null,
  accessToken: undefined,
  refreshToken: undefined,
};

// Handles user authentication and token management
const authSlice = createSlice({
  name: "auth",
  initialState,
  reducers: {},

  // Handles actions generated by async thunks
  extraReducers: (builder) => {
    // Handle successful login
    builder.addCase(
      loginThunk.fulfilled,
      (state, action: PayloadAction<AuthResponse>) => {
        const { accessToken, refreshToken, ...user } = action.payload;
        // Update Redux state with authenticated user info and token
        state.user = user;
        state.accessToken = accessToken;
        state.refreshToken = refreshToken;
      }
    );
    // Handle successful logout
    builder.addCase(logoutThunk.fulfilled, (state) => {
      // Clear all authentication-related data
      state.user = null;
      state.accessToken = undefined;
      state.refreshToken = undefined;
    });
  },
});

export default authSlice.reducer;
